[build]
  command = "cd webapp && npm run build"
  publish = "webapp/dist"
  functions = "netlify/functions"

[[redirects]]
  from   = "/api/v1/visualization/generate"
  to     = "/.netlify/functions/visualization-generate"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
